# Generated by Django 3.0.1 on 2020-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployeemodel',
            name='save',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
